### ISSUE TITLE
README.md misleading comments

### ISSUE THREAD

**Issue by richthedev** [hackathon-cognibox-team5/js-model#43]
Hi, the comments in the Instance Methods -> hasChanged section are misleading as they mention that the hasChanged method check the validity of the attribute.

user.attrs.username.hasChanged(); // check if the current attribute is valid
user.hasChanged(); // check if all attributes are valid

**Comment by BleuShan** [comment]
Thanks for noticing. I guess it's a copy paste error. 

IIRC, It's not completely misleading. At least, if you have something like this:

``` js
var User = Model.extend({
  name: "User"
  baseUrl: "http://hackathon.cognibox.net/",
  attrs: { "id": {}, "potato": {primary: true} }
  }, {
  fullName: function() { return this.firstName + this.lastName; }
  }, {
  hasChanged: function() { return this.isValid(); }
});
var user = User.create({"id": 1});
user.fetch();
user.attrs.username.hasChanged(); // check if the current attribute is valid.
```

@kazalt could probably confirm this. But yeah... we should fix this.
